### ISSUE TITLE
Bug: toFilterExpression overwrites filterExpression with last condition in contains OR contains filters

### ISSUE THREAD

**Issue by alkaline1024** [blueleader07/typeorm-dynamodb#12]
There seems to be a bug in the `toFilterExpression` function in `FindOptions.js`. When using multiple contains `conditions` with an `OR` operator (e.g., `contains(name, 'value') OR contains(description, 'value')`), the resulting filter expression only includes the last condition.

**For example:**
Use a filter with multiple contains conditions joined by OR (or AND):
`
FindOptions.toFilterExpression({
  filter: "contains(name, 'value') OR contains(description, 'value')"
});
`

**Expected Output:**
`contains(#name, :name) OR contains(#description, :description)`

**Actual Output:**
`contains(#description, :description)`

The issue occurs because `filterExpression` is overwritten during the loop that processes each condition in the `filter.split() `method **(line 135)**. Each processed condition **overwrites the previous value** of `filterExpression`.

### **Proposed Fix:**

To resolve this issue, modify the loop in toFilterExpression to accumulate all processed expressions instead of overwriting filterExpression. Below is a suggested fix:

```
static toFilterExpression(options) {
    if (options.filter) {
        const expressions = options.filter.split(/ and | or /gi); // Split by AND/OR
        const connectors = options.filter.match(/ and | or /gi) || []; // Extract AND/OR operators
        const processedExpressions = expressions.map(expression => {
            let processedExpression = containsToFilterExpression(expression.trim());
            if (!expression.toLowerCase().includes('contains(')) {
                const parts = property_parser_1.splitOperators(expression.trim());
                if (parts.length === 2) {
                    const name = parts[0].trim();
                    const value = parts[1].trim();
                    if (value.startsWith("'")) {
                        const re = new RegExp(`${name}(?=(?:(?:[^']*'){2})*[^']*$)`);
                        processedExpression = processedExpression.replace(re, `#${DynamoTextHelper_1.poundToUnderscore(name)}`);
                    } else if (value.startsWith('"')) {
                        const re = new RegExp(`${name}(?=(?:(?:[^"]*"){2})*[^"]*$)`);
                        processedExpression = processedExpression.replace(re, `#${DynamoTextHelper_1.poundToUnderscore(name)}`);
                    }
                    processedExpression = processedExpression.replace(value, `:${DynamoTextHelper_1.poundToUnderscore(name)}`);
                    processedExpression = processedExpression.replace(/['"]/g, '');
                } else {
                    throw Error(`Failed to convert filter to ExpressionAttributeValues: ${options.filter}`);
                }
            }
            return processedExpression;
        });

        // Combine processed expressions
        let finalFilterExpression = processedExpressions[0];
        for (let i = 1; i < processedExpressions.length; i++) {
            finalFilterExpression += ` ${connectors[i - 1].trim()} ${processedExpressions[i]}`;
        }

        return finalFilterExpression;
    }
    return undefined;
}
```
Please let me know if you need further clarification or assistance testing a fix for this issue. Thank you for your hard work on this library!

**Comment by blueleader07** [comment]
Good morning @alkaline1024 ,

Thanks for reporting the issue and offering the solution.  I've added a couple unit tests.  Looks like it works perfectly!  I've published a new version (typeorm-dynamodb@3.0.46).  Please give it a try and let me know if we need any further adjustments.

Have a great day.

Fixed:   https://github.com/blueleader07/typeorm-dynamodb/commit/add1a2761c0422dd654d0c83643048eb4f7da4be
